name: Integração Continua

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Set up Android
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build Android APK
        run: npm run android

      - name: Set up iOS
        run: npx pod-install
        working-directory: ios

      - name: Build iOS IPA
        run: npm run ios:build
