name: Integração Continua

on: pull_request

jobs:
  continuos-integrations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v2

      - name: Instalação do node.js
        uses: actions/setup-node@v2
        with:
         node-version: 16.18.1

      - name: instalar dependências e builda para android
        run: |
         yarn install    
         npx react-native run-android
