name: Integração Continua

on: [push, pull_request]

jobs:
  continuos-integrations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v2

      - name: Instalação do node.js
        uses: actions/setup-node@v2
        with:
         node-version: 14.18.1

      - name: instalar dependências 
        run: 
         yarn install   

      - name: build para android
        run: 
         yarn android
